import os
import sys
import requests
from google import genai

# Configuration from GitHub Environment
GEMINI_API_KEY = os.environ.get("GOOGLE_AI_STUDIO_API_KEY")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
REPO = os.environ.get("REPO")
PR_NUMBER = os.environ.get("PR_NUMBER")
PR_TITLE = os.environ.get("PR_TITLE", "Untitled PR")

def review_pr():
    client = genai.Client(api_key=GEMINI_API_KEY)
    
    # Read the diff generated by the Action
    try:
        with open("pr_diff.txt", "r") as f:
            diff = f.read()
    except FileNotFoundError:
        print("Diff file not found.")
        return "Error: Diff file missing."

    # Safety: Truncate diff if it exceeds context limits (~100k chars)
    if len(diff) > 80000:
        diff = diff[:80000] + "\n\n[... Diff truncated for length ...]"

    system_prompt = """
    You are a Senior Backend Engineer and CKA reviewing a PR for ResumeIQ.
    
    ## ARCHITECTURE RULES (ENFORCE STRICTLY):
    1. Database: We use a SINGLE PostgreSQL instance. Never suggest Firestore.
    2. JSONB: 'resume_data' uses JSONB. Top-level columns must be used for indexed fields (role, company).
    3. pgvector: We use Vector(3072) for gemini-embedding-001 outputs.
    4. Budget Guard: Pre-flight coin deduction in 'backend/core/budget_guard.py' must use 'SELECT ... FOR UPDATE'.
    5. Async: Every DB call must use SQLAlchemy 'AsyncSession' and 'async with' patterns.
    6. Auth: UID must come from 'verify_token' (Firebase Admin). Never trust user_id in the request body.
    
    ## FORMAT:
    - ✅ What Looks Good
    - 🚨 Critical Issues (Security, Auth, Budget Guard bypass)
    - ⚠️ Important Issues (Logic, Patterns)
    - 📊 Verdict: APPROVE | REQUEST CHANGES | BLOCK
    """

    print(f"Analyzing PR #{PR_NUMBER}: {PR_TITLE}...")
    
    response = client.models.generate_content(
        model='gemini-2.0-flash',
        contents=[system_prompt, f"PR Title: {PR_TITLE}\n\nDiff Content:\n{diff}"]
    )
    
    return response.text

def post_comment(text):
    url = f"https://api.github.com/repos/{REPO}/issues/{PR_NUMBER}/comments"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }
    # Formatting the comment for GitHub Markdown
    body = f"## 🤖 ResumeIQ AI Reviewer\n\n{text}\n\n---\n*Review powered by Gemini 2.0 Flash*"
    
    res = requests.post(url, json={"body": body}, headers=headers)
    if res.status_code == 201:
        print(f"✅ Successfully posted review to PR #{PR_NUMBER}")
    else:
        print(f"❌ Error posting comment: {res.status_code} - {res.text}")

if __name__ == "__main__":
    if not GEMINI_API_KEY or not GITHUB_TOKEN:
        print("Missing required environment variables.")
        sys.exit(1)
        
    review_output = review_pr()
    post_comment(review_output)